spring.application.name=RS

# H2 - Base de données
spring.datasource.url=jdbc:h2:mem:SansFiltre
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=ssf
spring.datasource.password=sansfiltre

# JPA - Création des tables automatiquement
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console